// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesCrudApp.Data;

#nullable disable

namespace MoviesCrudApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MoviesCrudApp.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Films d'action et d'aventure",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Films comiques et humoristiques",
                            Name = "Comédie"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Films dramatiques et émotionnels",
                            Name = "Drame"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Films de science-fiction",
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Films d'horreur et thriller",
                            Name = "Horreur"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Films romantiques",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Films d'animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Documentaires",
                            Name = "Documentaire"
                        });
                });

            modelBuilder.Entity("MoviesCrudApp.Models.MembershipType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MembershipTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Adhésion Bronze",
                            DiscountRate = 5m,
                            Name = "Bronze"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Adhésion Silver",
                            DiscountRate = 10m,
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Adhésion Gold",
                            DiscountRate = 15m,
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Adhésion Platinum",
                            DiscountRate = 20m,
                            Name = "Platinum"
                        });
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAjoutMovie")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAjoutMovie = new DateTime(2024, 10, 13, 14, 14, 2, 0, DateTimeKind.Unspecified),
                            Description = "Deux hommes emprisonnés créent un lien fort au fil des années.",
                            Duration = 142,
                            GenreId = 3,
                            ImageFile = "shawshank.jpg",
                            Rating = 9.3m,
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = 2,
                            DateAjoutMovie = new DateTime(2024, 10, 13, 14, 14, 2, 0, DateTimeKind.Unspecified),
                            Description = "Le patriarche vieillissant d'une dynastie criminelle transfère le contrôle à son fils réticent.",
                            Duration = 175,
                            GenreId = 3,
                            ImageFile = "godfather.jpg",
                            Rating = 9.2m,
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather"
                        },
                        new
                        {
                            Id = 3,
                            DateAjoutMovie = new DateTime(2024, 10, 13, 14, 14, 2, 0, DateTimeKind.Unspecified),
                            Description = "Batman affronte le Joker dans une bataille pour l'âme de Gotham City.",
                            Duration = 152,
                            GenreId = 1,
                            ImageFile = "darkknight.jpg",
                            Rating = 9.0m,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            DateAjoutMovie = new DateTime(2024, 10, 13, 14, 14, 2, 0, DateTimeKind.Unspecified),
                            Description = "Les vies de deux tueurs à gages, d'un boxeur et d'un gangster s'entremêlent.",
                            Duration = 154,
                            GenreId = 1,
                            ImageFile = "pulpfiction.jpg",
                            Rating = 8.9m,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        });
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Customer", b =>
                {
                    b.HasOne("MoviesCrudApp.Models.MembershipType", "MembershipType")
                        .WithMany("Customers")
                        .HasForeignKey("MembershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Movie", b =>
                {
                    b.HasOne("MoviesCrudApp.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MoviesCrudApp.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MoviesCrudApp.Models.MembershipType", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
